export const BROWSER_SESSION_PROVIDER = {
  LINKEDIN_JOBS: 'LINKEDIN_JOBS',
  LINKEDIN_FEED: 'LINKEDIN_FEED',
  LINKEDIN_POST_SEARCH: 'LINKEDIN_POST_SEARCH',
};

export const BROWSER_SESSION_STATUS = {
  ACTIVE: 'ACTIVE',
  ATTENTION_REQUIRED: 'ATTENTION_REQUIRED',
  CLOSED: 'CLOSED',
  ERROR: 'ERROR',
};
